version: '3.8'

services:
  web-api:
    build: .
    container_name: carol_app_web
    ports:
      - "5005:5000"
    environment:
      - PORT=5000
      - REDIS_URL=redis://carol_redis_cache:6379
    depends_on:
      - redis-cache
    networks:
      - carol-rede-binario

  redis-cache:
    image: redis:7-alpine
    container_name: carol_redis_cache
    ports:
      - "6379:6379"
    volumes:
      - carol_redis_data:/data
    networks:
      - carol-rede-binario

networks:
  carol-rede-binario:
    driver: bridge

volumes:
  carol_redis_data:

